services:
  proxylib:
    build: .
    container_name: proxy
    volumes:
      - django_static:/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - appnet

networks:
  appnet:
    external: true

volumes:
  django_static:
    external: true
